### ISSUE TITLE
I broke it :(

### ISSUE THREAD

**Issue by brianteeman** [brianteeman/tasklist#1]
In the process of converting this script to Joomla and supporting language files I have broken the functionality of the "Clear Completed" button.

It worked perfectly outside of joomla https://codepen.io/brianteeman/pen/RwJopqV

I just can't see what is different to produce the error
```
admin-tasklist.js?ece6dd409db6ff4965a740b51c4cc8e5:38 Uncaught ReferenceError: deleteIndexes is not defined
    at HTMLButtonElement.
```

@dgrammatiko any suggestion?

**Comment by dgrammatiko** [comment]
#2 should fix the error above
