### ISSUE TITLE
Site-based tasks, not browser-based

### ISSUE THREAD

**Issue by mariantanase** [brianteeman/tasklist#5]
Case study:

- I work on site A where I have installed the tasklist module and where I added 2 tasks;
- Now I switch on the site B where tasklist module is allready installed. When I click on "Task List" I see the same 2 tasks from the first site.

Question:
- It's possible to display tasks according to the displayed site? not cumulative?

I do not know if I have explained myself.

**Comment by brianteeman** [comment]
yes I understand you. 

are the sites on the same domain name?

**Comment by mariantanase** [comment]
No, I'm on a localhost LAMP.

http://localhost/siteA/
http://localhost/siteB/
...

**Comment by brianteeman** [comment]
thats the reason. it stores the data in local storage and this is per domain - so it sees both of those as the same domain.

if it was a live site example.com then you would not see the data from example2.com and vice versa

**Comment by mariantanase** [comment]
OK, I installed the module on the two different live domains and I can confirm that the tasks are domain-based.
Thanks!
